[package]
name = "sas-rs-uuidv7"
version = "0.1.0"
edition = "2021"
description = "UUIDv7 generation for SAS"
authors = ["Carus11"]

[lib]
name = "sas_rs_uuidv7"
crate-type = ["cdylib"]

[dependencies]
uuid = { version = "1.7.0", features = ["v7"] }
libc = "0.2.152"
